"""New column

Revision ID: 26be61f2f3e1
Revises: 9051cd7a46a9
Create Date: 2024-12-24 18:05:46.965698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26be61f2f3e1'
down_revision: Union[str, None] = '9051cd7a46a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Todo', 'important')
    # ### end Alembic commands ###
